sonar.projectKey=FarmVivi_discordbot-core
sonar.organization=farmvivi

# Encodage du code source
sonar.sourceEncoding=UTF-8

# Exclusions globales (les modules Maven sont détectés automatiquement par le scanner Maven)
sonar.exclusions=**/target/**,**/bin/**

# Version de Java utilisée pour l'analyse
sonar.java.source=17
