sonar.projectKey=FarmVivi_discordbot-core
sonar.organization=farmvivi

# Multi-module configuration
# API Module
discordbot-api.sonar.sources=discordbot-api/src/main/java
discordbot-api.sonar.java.binaries=discordbot-api/target/classes

# Core Module  
discordbot-core.sonar.sources=discordbot-core/src/main/java
discordbot-core.sonar.java.binaries=discordbot-core/target/classes

# Example Audio Module
discordbot-example-audio.sonar.sources=discordbot-example-audio/src/main/java
discordbot-example-audio.sonar.java.binaries=discordbot-example-audio/target/classes

# Encodage du code source
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/target/**,**/bin/**

# Version de Java
sonar.java.source=17
